#!/bin/bash
PROJECT_PATH=$(dirname "$0")

compile() {
	cd "$PROJECT_PATH"
	cd ../../..
	cd styleguide/structure/_node-files
	node write-date-exec.js
	cd ../../..
	STYLEGUIDE_COMPILE=1 ./styleguide/structure/_node-files/node_modules/.bin/harp compile
	cd www
	find . -type f -name "*.html" -exec ../styleguide/structure/_node-files/node_modules/.bin/js-beautify -r {} \;
	find . -type f -name "*.js" -exec ../styleguide/structure/_node-files/node_modules/.bin/js-beautify -r {} \;
	find . -type f -name "*.css" -exec ../styleguide/structure/_node-files/node_modules/.bin/js-beautify -r {} \;
	rm -rf AUTHORS.html Compile.app/ README.html CONTRIBUTING.html LICENSE.html Start.app/ livereload.js
	echo "Done! Compiled HTML in the www folder."
	echo "PROGRESS:100"
}

echo "Compiling Styleguide..."
echo ""
echo "PROGRESS:0"
if [ ! -f ../../../styleguide/structure/_node-files/node_modules/.bin/harp ]
then
    echo "Harp wasn't found, please run the Start file."
else
	compile
fi
