#!/bin/bash
PROJECT_PATH=$(dirname "$0")

compile() {
	cd "$PROJECT_PATH"
	cd ../../..
	cd styleguide/structure/_node-files
	node write-date-exec.js
	cd ../../..
	harp compile
	cd www
	find . -type f -name "*.html" -exec js-beautify -r {} \;
	find . -type f -name "*.js" -exec js-beautify -r {} \;
	find . -type f -name "*.css" -exec js-beautify -r {} \;
	echo "Done! Compiled HTML in the www folder."
	echo "PROGRESS:100"
}

echo "Compiling Styleguide..."
echo ""
echo "PROGRESS:0"
type harp >/dev/null 2>&1
if [ $? -eq 1 ]
then
    echo "Harp wasn't found, please run the Start file."
else
	compile
fi

