#!/bin/bash
PROJECT_PATH=$(dirname "$0")

installNode() {
	xcode-select --install
	xcode-select -p >/dev/null 2>&1
	while [ ! $? -eq 0 ];
	do
		echo "Waiting for installing XCode"
		sleep 1
		xcode-select -p >/dev/null 2>&1
	done
	printf "\nInstalling Node.js...\n"
	cd ~
	echo 'export PATH=$HOME/local/bin:$PATH' >> .bashrc
	. .bashrc
	mkdir local
	mkdir node-latest-install
	cd node-latest-install
	curl https://nodejs.org/download/release/v0.12.7/node-v0.12.7.tar.gz | tar xz --strip-components=1
	./configure --prefix=../local
	make install
	curl -L https://www.npmjs.org/install.sh | sh
}

run() {
	cd ~
	. .bashrc
	cd "$PROJECT_PATH"
	printf "\nChecking dependencies...\n\n"
	type harp >/dev/null 2>&1
	if [ $? -eq 1 ]
	then
		npm install harp -g
	fi
	type js-beautify >/dev/null 2>&1
	if [ $? -eq 1 ]
	then
		npm install js-beautify -g
	fi
	cd ../../../styleguide/structure/_node-files
	npm install
	echo "PROGRESS:80"
	createLockFile
	cd styleguide/structure/_node-files
	printf "\nLet's start this thing...\n"
	node watch.js
	echo "PROGRESS:100"
}

createLockFile() {
	cd "$PROJECT_PATH"
	cd ../../..
	if [ ! -f .install.lock ]; then
		touch .install.lock
	fi
}
. ~/.bashrc
echo "Styleguide. Welcome!"
cd ../../..                      
if [ ! -f .install.lock ]; then
	echo "PROGRESS:0"
	type node >/dev/null 2>&1
	if [ $? -eq 1 ]
	then
		type nvm >/dev/null 2>&1
		if [ $? -eq 1 ]
		then
      			installNode
      			echo "PROGRESS:50"
      			run
	    	fi
	else
	    echo "PROGRESS:50"
	    run
	fi
else
	echo "PROGRESS:50"
	run
fi
